favicon: assets/icons/favicon.ico
apple_touch_icon: assets/icons/icon-192x192.png
android_chrome_192: assets/icons/icon-192x192.png
android_chrome_512: assets/icons/icon-512x512.png

title: My Website
description: This is my website.
primary_color: #007bff
secondary_color: #6c757d
