# theme of the website 
remote_theme: hydecorp/hydejack@v9.1.6

# icon of the website
favicon: "/favicon.png"

# title of the website
title:                 Hasan Saygınel

# sidebar
menu:
  - title: Blog
    url:   /blog/
  - title: Projects
    url:   /projects/
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/

# sidebar image
accent_image:          /assets/img/f10_dilution_fridge.png # Morton Lab (F10 dilution fridge)
accent_color:          rgb(79,177,186)


# plugins
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at
