remote_theme: hydecorp/hydejack@v9.1.6
plugins:
  - jekyll-include-cache 

menu:
  - title: Blog
    url:   /blog/
  - title: Projects
    url:   /projects/
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/

accent_image:          /assets/img/f10_dilution_fridge.png
accent_color:          rgb(79,177,186)
