remote_theme: hydecorp/hydejack@v9.1.6
plugins:
  - jekyll-include-cache

image:
  path:    /assets/img/f10_dilution_fridge.png

menu:
  - title: Blog
    url:   /blog/
  - title: Projects
    url:   /projects/
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/
