favicon: /path/to/favicon.png
apple_touch_icon: /path/to/apple-touch-icon.png
android_chrome_192: /path/to/android-chrome-192x192.png
android_chrome_512: /path/to/android-chrome-512x512.png

title: My Website
description: This is my website.
primary_color: #007bff
secondary_color: #6c757d
